name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - uses: textbook/git-checkout-submodule-action@2.1.1

    - run: make v8

    - run: mkdir output

    - run: cp -r ./v8/include ./output/.

    - run: cp -r ./v8/out.gn ./output/.

    - uses: actions/upload-artifact@v2
      with:
        name: v8-artifact
        path: |
          output

    - uses: actions/download-artifact@v2
      with:
        name: v8-artifact
